PersonalCollections/Models/ViewModel/HomeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PersonalCollections.Models.ViewModel
{
    public class HomeViewModel
    {
        public List<CollectionItem> CollectionItems { get; set; }
        public List<Item> Items { get; set; }
    }
}

PersonalCollections/Controllers/CollectionController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PersonalCollections.Models;
using PersonalCollections.Models.ViewModel;

namespace PersonalCollections.Controllers
{
    public class CollectionController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly PersonalCollectionContext db;
        private readonly IWebHostEnvironment _appEnvironment;
        public CollectionController(UserManager<User> userManager, PersonalCollectionContext context, IWebHostEnvironment appEnvironment)
        {
            _userManager = userManager;
            db = context;
            _appEnvironment = appEnvironment;
        }
        public IActionResult CreateCollection()
        {
            SelectList themas = new SelectList(db.Themas, "IdThema", "Name");
            ViewBag.Thema = themas;
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateCollection(CollectionItem collectionItem, IFormFile uploadedFile)
        {
            Thema thema = await db.Themas.FirstOrDefaultAsync(p => p.IdThema == collectionItem.IdThema);
            User user = await _userManager.FindByNameAsync(User.Identity.Name);
            collectionItem.Themas = thema;
            collectionItem.IdUser = user.Id;

            if (uploadedFile != null)
            {
                // путь к папке Files
                string path = "/Files/" + uploadedFile.FileName;
                // сохраняем файл в папку Files в каталоге wwwroot
                using (var fileStream = new FileStream(_appEnvironment.WebRootPath + path, FileMode.Create))
                {
                    await uploadedFile.CopyToAsync(fileStream);
                }
                collectionItem.Image = path;
            }

            db.CollectionItems.Add(collectionItem);
            await db.SaveChangesAsync();
            return RedirectToAction("EditCollection", new { id = collectionItem.IdCollection});
        }
        public IActionResult CreateItem(int id)
        {
            ViewBag.Id = id;
            return View();
        }
        public async Task<IActionResult> EditItem(int id)
        {
            Item item = await db.Items.Include(x => x.CollectionItems).FirstOrDefaultAsync(x => x.IdItem == id);
            return View(item);
        }
        [HttpPost]
        public async Task<IActionResult> CreateItem(Item item, int IdCollectionItem)
        {
            CollectionItem collection = await db.CollectionItems.FirstOrDefaultAsync(p => p.IdCollection == IdCollectionItem);
            item.IdCollectionItem = IdCollectionItem;
            item.CollectionItems = collection;
            db.Items.Add(item);
            await db.SaveChangesAsync();
            return RedirectToAction("EditCollection", new { id = IdCollectionItem});
        }
        [HttpPost]
        public async Task<IActionResult> EditItem(Item item)
        {
            CollectionItem collection = await db.CollectionItems.FirstOrDefaultAsync(p => p.IdCollection == item.IdCollectionItem);
            item.CollectionItems = collection;
            db.Items.Update(item);
            await db.SaveChangesAsync();
            return RedirectToAction("EditCollection", new { id = item.IdCollectionItem });
        }
        public async Task<IActionResult> DetailsItem(int id)
        {
            Item item = await db.Items.Include(p => p.CollectionItems).FirstOrDefaultAsync(i => i.IdItem == id);
            return View(item);
        }
        [HttpGet]
        public async Task<IActionResult> EditCollection(int id)
        {
            SelectList themas = new SelectList(db.Themas, "IdThema", "Name");
            ViewBag.Thema = themas;
            CollectionItem item = await db.CollectionItems.Include(x => x.Themas).Include(x => x.Items).FirstOrDefaultAsync(x => x.IdCollection == id);
            ViewBag.Image = item.Image;
            return View(item);
        }
        [HttpPost]
        public async Task<IActionResult> EditCollection(CollectionItem item, IFormFile uploadedFile, string Image)
        {
            Thema thema = await db.Themas.FirstOrDefaultAsync(p => p.IdThema == item.IdThema);
            item.Themas = thema;
            string image = Image;
            if (uploadedFile != null)
            {
                // путь к папке Files
                string path = "/Files/" + uploadedFile.FileName;
                // сохраняем файл в папку Files в каталоге wwwroot
                if (image != path)
                {
                    item.Image = path;
                    if (image != null)
                    {
                        string paths = _appEnvironment.WebRootPath + Image;
                        FileInfo fileInf = new FileInfo(paths);
                        if (fileInf.Exists)
                        {
                            fileInf.Delete();
                        }
                    }
                    using (var fileStream = new FileStream(_appEnvironment.WebRootPath + path, FileMode.Create))
                    {
                        await uploadedFile.CopyToAsync(fileStream);
                    }
                }
                else
                {
                    item.Image = ViewBag.Image;
                }  
            }
            db.CollectionItems.Update(item);
            await db.SaveChangesAsync();
            return RedirectToAction("Index", "Manage");
        }

        public async Task<IActionResult> DeleteCollection(int id)
        {
            CollectionItem collection = await db.CollectionItems.Include(x => x.Items).FirstOrDefaultAsync(x => x.IdCollection == id);
            if (collection != null)
            {
                foreach (Item item in collection.Items)
                {
                    Item item1 = await db.Items.Include(x => x.Likes).FirstOrDefaultAsync(x => x.IdItem == item.IdItem);
                    if (item1 != null)
                    {
                        foreach (Like like in item1.Likes)
                        {
                            db.Likes.Remove(like);
                        }
                        db.Items.Remove(item1);
                    }
                }
                db.CollectionItems.Remove(collection);
            }
            await db.SaveChangesAsync();
            return RedirectToAction("ListCollection", "Admin");
        }
        public async Task<IActionResult> Item(int id)
        {
            Item item = await db.Items.Include(p => p.CollectionItems).Include(x => x.Likes).FirstOrDefaultAsync(i => i.IdItem == id);
            LikeViewModel model = new LikeViewModel();
            if (item != null)
            {
                model.like = false;
                model.NameItem = item.NameItem;
                model.Description = item.Description;
                model.IdCollectionItem = item.IdCollectionItem;
                model.NameCollection = item.CollectionItems.NameCollection;
                model.IdItem = item.IdItem;
                model.Image = item.CollectionItems.Image;
                for (int i = 0; i < item.Likes.Count; i++)
                    if (item.Likes[i].UserName == User.Identity.Name)
                        model.like = true;
            }
            return View(model);
        }
        public async Task<IActionResult> LikeUp(int id)
        {
            Like like = new Like
            {
                IdItem = id,
                Item = await db.Items.FirstOrDefaultAsync(x => x.IdItem == id),
                UserName = User.Identity.Name
            };
            db.Likes.Add(like);
            await db.SaveChangesAsync();
            return RedirectToAction("Item", new { id = like.IdItem});
        }
        public async Task<IActionResult> LikeDelete(int id)
        {
            Like like = await db.Likes.FirstOrDefaultAsync(x => x.IdItem == id && x.UserName == User.Identity.Name);
            if(like != null)
            {
                db.Likes.Remove(like);
            }
            await db.SaveChangesAsync();
            return RedirectToAction("Item", new { id = like.IdItem });
        }
        public async Task<IActionResult> UserCollection(string id)
        {
            ViewBag.Id = id;
            var collection = db.CollectionItems.Where(x => x.IdUser == id).Include(x => x.Themas).Include(x => x.Items);
            return View(collection);
        }
        public async Task<IActionResult> DeleteItem(int id)
        {
            
            Item item = await db.Items.Include(x => x.Likes).FirstOrDefaultAsync(x => x.IdItem == id);
            int idCollection = item.IdCollectionItem;
            if (item != null)
            {
                if (item.Likes != null)
                {
                    foreach (Like like in item.Likes)
                    {
                        db.Likes.Remove(like);
                    }
                }
                TempData["messageDelete"] = String.Format("Item {0} delete", item.NameItem);
                db.Items.Remove(item);
                await db.SaveChangesAsync();
            }
            
            return RedirectToAction("EditCollection", new { id = idCollection });
        }
    }
}

PersonalCollections/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using PersonalCollections.Models;
using PersonalCollections.Models.ViewModel;

namespace PersonalCollections.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly PersonalCollectionContext db;

        public HomeController(ILogger<HomeController> logger, PersonalCollectionContext context)
        {
            _logger = logger;
            db = context;
        }


        public async Task<IActionResult> Index()
        {
            HomeViewModel model = new HomeViewModel();
            List<CollectionItem> collectionItems = new List<CollectionItem>();
            List<Item> Items = new List<Item>();
            List<CollectionItem> collections = await db.CollectionItems.Include(x => x.Themas).Include(x => x.Items).OrderByDescending(x => x.Items.Count).ToListAsync();
            if(collections.Count() > 6)
            {
                for (int i = 0; i < 6; i++)
                    collectionItems.Add(collections[i]);
                model.CollectionItems = collectionItems;
            }
            else
            {
                model.CollectionItems = collections;
            }

            List<Item> items = await db.Items.Include(x => x.CollectionItems).Include(x => x.Likes).OrderByDescending(x => x.Likes.Count()).ToListAsync();
            if (items.Count() > 6)
            {
                for (int i = 0; i < 6; i++)
                    Items.Add(items[i]);
                model.Items = Items;
            }
            else
            {
                model.Items = items;
            }   
            return View(model);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [HttpPost]
        public IActionResult SetLanguage(string culture, string returnUrl)
        {
            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
            );

            return LocalRedirect(returnUrl);
        }
        public async Task<IActionResult> DetailsCollecton(int id)
        {
            CollectionItem item = await db.CollectionItems.Include(x => x.Themas).Include(x => x.Items).FirstOrDefaultAsync(x => x.IdCollection == id);
            return View(item);
        }
        private int pageSize = 6;
        public async Task<IActionResult> AllCollection(int page = 1)
        {
            IQueryable<CollectionItem> source = db.CollectionItems.Include(x => x.Themas);
            var count = await source.CountAsync();
            var Collections = await source.Skip((page - 1) * pageSize).Take(pageSize).ToListAsync();

            Page pageViewModel = new Page(count, page, pageSize);
            IndexViewModel viewModel = new IndexViewModel
            {
                Page = pageViewModel,
                CollectionItems = Collections
            };
            return View(viewModel);
        }
        public async Task<IActionResult> AllItem(int page = 1)
        {
            IQueryable<Item> source = db.Items.Include(x => x.CollectionItems);
            var count = await source.CountAsync();
            var items = await source.Skip((page - 1) * pageSize).Take(pageSize).ToListAsync();

            Page pageViewModel = new Page(count, page, pageSize);
            IndexViewModel viewModel = new IndexViewModel
            {
                Page = pageViewModel,
                Items = items
            };
            return View(viewModel);
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PersonalCollections/Views/Home/AllCollection.cshtml
@model IndexViewModel

@{
    ViewData["Title"] = "AllCollection";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card card-bordered mt-3">
    <div class="card-header bg-gradient-dark">
        <h2 class="font-weight-bold">Популярные </h2>
    </div>
    <div class="card-body bg-gradient-light">
        <div class="row">
            @foreach (var item in Model.CollectionItems)
            {
                <div class="col-lg-4 col-md-6 mt-3">
                    <div class="card card-bordered">
                        <img class="card-img-top img-fluid" src="@Url.Content(item.Image)" alt="image">
                        <div class="card-body">
                            <h5 class="title">@item.NameCollection</h5>
                            @if (item.Description != null)
                            {
                                @if (item.Description.Length > 100)
                                {
                                    <p class="card-text">
                                        @item.Description.Substring(0, 100) ...
                                    </p>
                                }
                                else
                                {
                                    <p class="card-text">
                                        @item.Description
                                    </p>
                                }
                            }
                            <a asp-action="DetailsCollecton" asp-route-id="@item.IdCollection" class="btn btn-primary">@Localizer["Detail"]</a>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
    <div class="card-footer">
        @if (Model.Page.HasPreviousPage)
        {
            <a asp-action="AllCollection"
               asp-route-page="@(Model.Page.PageNumber - 1)"
               class="btn btn-outline-dark">
                <i class="glyphicon glyphicon-chevron-left"></i>
                Назад
            </a>
        }
        @if (Model.Page.HasNextPage)
        {
            <a asp-action="AllCollection"
               asp-route-page="@(Model.Page.PageNumber + 1)"
               class="btn btn-outline-dark">
                Вперед
                <i class="glyphicon glyphicon-chevron-right"></i>
            </a>
        }
    </div>
</div>

PersonalCollections/Views/Home/AllItem.cshtml
@model IndexViewModel
@{
    ViewData["Title"] = "AllItem";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="card card-bordered mt-3">
    <div class="card-header bg-gradient-dark">
        <h2 class="font-weight-bold ">Полулярные Айтемы</h2>
    </div>
    <div class="card-body bg-gradient-light">
        <div class="row">
            @foreach (var item in Model.Items)
            {
                <div class="col-lg-4 col-md-6 mt-2">
                    <div class="card card-bordered">
                        <img class="card-img-top img-fluid" src="@Url.Content(item.CollectionItems.Image)" alt="image">
                        <div class="card-body">
                            <h5 class="title">@item.NameItem</h5>
                            @if (item.Description != null)
                            {
                                @if (item.Description.Length > 100)
                                {
                                    <p class="card-text">
                                        @item.Description.Substring(0, 100) ...
                                    </p>
                                }
                                else
                                {
                                    <p class="card-text">
                                        @item.Description
                                    </p>
                                }
                            }
                            <a asp-action="Item" asp-controller="Collection" asp-route-id="@item.IdItem" class="btn btn-primary">@Localizer["Detail"]</a>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
    <div class="card-footer">
        @if (Model.Page.HasPreviousPage)
        {
            <a asp-action="AllItem"
               asp-route-page="@(Model.Page.PageNumber - 1)"
               class="btn btn-outline-dark">
                <i class="glyphicon glyphicon-chevron-left"></i>
                Назад
            </a>
        }
        @if (Model.Page.HasNextPage)
        {
            <a asp-action="AllItem"
               asp-route-page="@(Model.Page.PageNumber + 1)"
               class="btn btn-outline-dark">
                Вперед
                <i class="glyphicon glyphicon-chevron-right"></i>
            </a>
        }
    </div>
</div>

PersonalCollections/Views/Home/DetailsCollecton.cshtml
@model PersonalCollections.Models.CollectionItem

@{
    ViewData["Title"] = Model.NameCollection;
    Layout = "~/Views/Shared/_Layout.cshtml";
}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-action="Index">@Localizer["Home"]</a></li>
            <li class="breadcrumb-item active" aria-current="page">@Model.NameCollection</li>
        </ol>
    </nav>
<div>
    <main style="background: url('@Url.Content(Model.Image)')">
        <div class="page-header pb-10">
            <div class="container-fluid">
                <div class="page-header-content">
                    <h1 class="page-header-title">
                        <span>@Model.NameCollection</span>
                    </h1>
                    <div class="page-header-subtitle">@Model.Themas.Name</div>
                </div>
            </div>
        </div>
        <div class="container-fluid mt-n10">
            <div class="card">
                <div class="card-header"> @Localizer["Description"]</div>
                <div class="card-body">
                    <p class="text-justify">
                        @Html.DisplayFor(model => model.Description)
                    </p>
                </div>
            </div>
            <br />
            <div class="card mb-3">
                <div class="card-header">@Localizer["Theme"] </div>
                <div class="card-body">
                    <ul>
                        @foreach (var item in Model.Items)
                        {
                            <li><a asp-controller="Collection" asp-action="Item" asp-route-id="@item.IdItem">@item.NameItem</a></li>
                        }
                    </ul>
                </div>
            </div>
        </div>
        <hr />

    </main>
</div>
<nav>
    <div class="text-right">
        <a asp-action="Index">@Localizer["Back"]</a>
    </div>
</nav>

PersonalCollections/Views/Home/Index.cshtml
@model IEnumerable<CollectionItem>
@{
    ViewData["Title"] = "Home Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="text-center">
    <h2 class="font-weight-bold">Gjgekzhyst</h2>
    <hr class="mb-5" />
</section>
<div class="row">
        @foreach (var item in Model)
        {
            <div class="col-lg-4 col-md-6 mt-5">
                <div class="card card-bordered">
                    <img class="card-img-top img-fluid" src="@Url.Content(item.Image)" alt="image">
                    <div class="card-body">
                        <h5 class="title">@item.NameCollection</h5>
                        @*@if (@item.Description.Length > 100)
                        {
                            <p class="card-text">
                                @item.Description.Substring(0, 100) ...
                            </p>
                        }
                        else
                        {
                            <p class="card-text">
                                @item.Description
                            </p>
                        }*@

                        <a asp-action="DetailsCollecton" asp-route-id="@item.IdCollection" class="btn btn-primary">@Localizer["Detail"]</a>
                    </div>
                </div>
            </div>
        }
</div>